// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies;

public class MessagesHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messagesHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobile.MessagesHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		hasMessages("hasMessages"),
		Total("Total"),
		Search("Search"),
		SearchBoxReturnKey("SearchBoxReturnKey"),
		MessageBoxReturnKey("MessageBoxReturnKey"),
		MessageBoxExpanded("MessageBoxExpanded"),
		MessageText("MessageText");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MessagesHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MessagesHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messagesHelperMendixObject)
	{
		if (messagesHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!messagesHelperMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.messagesHelperMendixObject = messagesHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativemobile.proxies.MessagesHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobile.proxies.MessagesHelper(context, mendixObject);
	}

	public static nativemobile.proxies.MessagesHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobile.proxies.MessagesHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of hasMessages
	 */
	public final java.lang.Boolean gethasMessages()
	{
		return gethasMessages(getContext());
	}

	/**
	 * @param context
	 * @return value of hasMessages
	 */
	public final java.lang.Boolean gethasMessages(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.hasMessages.toString());
	}

	/**
	 * Set value of hasMessages
	 * @param hasmessages
	 */
	public final void sethasMessages(java.lang.Boolean hasmessages)
	{
		sethasMessages(getContext(), hasmessages);
	}

	/**
	 * Set value of hasMessages
	 * @param context
	 * @param hasmessages
	 */
	public final void sethasMessages(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasmessages)
	{
		getMendixObject().setValue(context, MemberNames.hasMessages.toString(), hasmessages);
	}

	/**
	 * @return value of Total
	 */
	public final java.lang.Integer getTotal()
	{
		return getTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of Total
	 */
	public final java.lang.Integer getTotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Total.toString());
	}

	/**
	 * Set value of Total
	 * @param total
	 */
	public final void setTotal(java.lang.Integer total)
	{
		setTotal(getContext(), total);
	}

	/**
	 * Set value of Total
	 * @param context
	 * @param total
	 */
	public final void setTotal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer total)
	{
		getMendixObject().setValue(context, MemberNames.Total.toString(), total);
	}

	/**
	 * @return value of Search
	 */
	public final java.lang.String getSearch()
	{
		return getSearch(getContext());
	}

	/**
	 * @param context
	 * @return value of Search
	 */
	public final java.lang.String getSearch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Search.toString());
	}

	/**
	 * Set value of Search
	 * @param search
	 */
	public final void setSearch(java.lang.String search)
	{
		setSearch(getContext(), search);
	}

	/**
	 * Set value of Search
	 * @param context
	 * @param search
	 */
	public final void setSearch(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String search)
	{
		getMendixObject().setValue(context, MemberNames.Search.toString(), search);
	}

	/**
	 * @return value of SearchBoxReturnKey
	 */
	public final java.lang.String getSearchBoxReturnKey()
	{
		return getSearchBoxReturnKey(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchBoxReturnKey
	 */
	public final java.lang.String getSearchBoxReturnKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SearchBoxReturnKey.toString());
	}

	/**
	 * Set value of SearchBoxReturnKey
	 * @param searchboxreturnkey
	 */
	public final void setSearchBoxReturnKey(java.lang.String searchboxreturnkey)
	{
		setSearchBoxReturnKey(getContext(), searchboxreturnkey);
	}

	/**
	 * Set value of SearchBoxReturnKey
	 * @param context
	 * @param searchboxreturnkey
	 */
	public final void setSearchBoxReturnKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String searchboxreturnkey)
	{
		getMendixObject().setValue(context, MemberNames.SearchBoxReturnKey.toString(), searchboxreturnkey);
	}

	/**
	 * @return value of MessageBoxReturnKey
	 */
	public final java.lang.String getMessageBoxReturnKey()
	{
		return getMessageBoxReturnKey(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageBoxReturnKey
	 */
	public final java.lang.String getMessageBoxReturnKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MessageBoxReturnKey.toString());
	}

	/**
	 * Set value of MessageBoxReturnKey
	 * @param messageboxreturnkey
	 */
	public final void setMessageBoxReturnKey(java.lang.String messageboxreturnkey)
	{
		setMessageBoxReturnKey(getContext(), messageboxreturnkey);
	}

	/**
	 * Set value of MessageBoxReturnKey
	 * @param context
	 * @param messageboxreturnkey
	 */
	public final void setMessageBoxReturnKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String messageboxreturnkey)
	{
		getMendixObject().setValue(context, MemberNames.MessageBoxReturnKey.toString(), messageboxreturnkey);
	}

	/**
	 * @return value of MessageBoxExpanded
	 */
	public final java.lang.Boolean getMessageBoxExpanded()
	{
		return getMessageBoxExpanded(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageBoxExpanded
	 */
	public final java.lang.Boolean getMessageBoxExpanded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MessageBoxExpanded.toString());
	}

	/**
	 * Set value of MessageBoxExpanded
	 * @param messageboxexpanded
	 */
	public final void setMessageBoxExpanded(java.lang.Boolean messageboxexpanded)
	{
		setMessageBoxExpanded(getContext(), messageboxexpanded);
	}

	/**
	 * Set value of MessageBoxExpanded
	 * @param context
	 * @param messageboxexpanded
	 */
	public final void setMessageBoxExpanded(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean messageboxexpanded)
	{
		getMendixObject().setValue(context, MemberNames.MessageBoxExpanded.toString(), messageboxexpanded);
	}

	/**
	 * @return value of MessageText
	 */
	public final java.lang.String getMessageText()
	{
		return getMessageText(getContext());
	}

	/**
	 * @param context
	 * @return value of MessageText
	 */
	public final java.lang.String getMessageText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MessageText.toString());
	}

	/**
	 * Set value of MessageText
	 * @param messagetext
	 */
	public final void setMessageText(java.lang.String messagetext)
	{
		setMessageText(getContext(), messagetext);
	}

	/**
	 * Set value of MessageText
	 * @param context
	 * @param messagetext
	 */
	public final void setMessageText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String messagetext)
	{
		getMendixObject().setValue(context, MemberNames.MessageText.toString(), messagetext);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messagesHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobile.proxies.MessagesHelper that = (nativemobile.proxies.MessagesHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
