// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("d7e0cc6a-b2c9-456e-8f14-36f4724dd39c"),
	startsWith("b2a6bfd0-db11-42d4-b49d-11984c316f94"),
	endsWith("ed49052d-a88d-427c-be50-490481e28251"),
	between("726f6391-8ae3-4a77-abb5-513d580908ce"),
	greater("fdf2ab3f-5c17-4076-89be-604ae7f9c4bc"),
	greaterEqual("733d212e-00f8-4962-99ce-a18efdf930dd"),
	equal("1e24c2cf-7b14-45c5-97ad-1f2c78b608cf"),
	notEqual("569e120a-b75a-4298-8686-d3db2f5b0309"),
	smaller("42efe689-60fd-4759-add6-9d56259b1285"),
	smallerEqual("99e21f24-d305-4fa1-94a6-680e26799ea6"),
	empty("89c884b3-527e-4b22-8095-f73856073fc0"),
	notEmpty("13b70d56-b8c4-426d-877c-1c7ed5718ed6");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
