// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feedbackmodule.proxies;

public enum TranslationLanguages
{
	Dutch("3af99a7b-2339-4393-8f9c-a6c7b114458e"),
	English("a5a68ea4-7c12-43b3-b9c8-ab66c85ae2ec"),
	French("f80a285f-e450-4f35-bd78-5a488f5d6735"),
	German("2ecd1e60-494e-46c9-add4-10663195efb1"),
	Hindi("09c0858c-0be1-438f-a557-e7fbbbcf13a1"),
	Portuguese("3c782c11-9a7c-49ec-bc59-43a0b4fe7e15"),
	Spanish("2205e2f4-441d-44a1-8fbb-12b699850730"),
	Turkish("6703448f-3e8f-4661-baab-7af49ada5af6");

	private final java.lang.String i18nCaptionKey;
	
	private TranslationLanguages(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
