// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("8509c28a-1350-475c-b787-c55e9728a423"),
	denied("dfdf6f98-5697-4049-bbf1-4b5422834039"),
	limited("1d2715de-08ba-4fa6-b3ef-94d01554e2c7"),
	granted("3ca790c2-3539-48b8-b8f3-84c342865e59"),
	blocked("6ffc5971-827c-4eee-bc38-61ac0918653a");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
