// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("efebb0fd-8c6c-464f-901f-308f4e114c3e"),
	low("f6e83763-7e15-4f14-83cb-2980cc58e761"),
	medium("76fde0b3-1902-4268-bb74-5c615511b219"),
	high("65c81c40-8ab4-4120-9507-9042ef0bd281"),
	custom("4c8fdf1c-2636-4dbd-856d-db537b9d3f42");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
