// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum Enum_DistanceUnit
{
	KILOMETER("204c0991-f34a-40a8-ae8c-913c8dbbb885"),
	STATUTE_MILE("b31b598f-f1e5-4ba4-ac42-b3cbfa689f92"),
	NAUTICAL_MILE("351c8772-9573-4ba4-8bef-6ae70602c159");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_DistanceUnit(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
