// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("aad98b30-5391-4863-b4a5-b18271f0db98"),
	Geocodio("1cf0c130-e868-47e7-9ffa-d92ef3bd0c3e"),
	LocationIQ("e9984738-8862-48a4-8014-1f713bc2d9b2"),
	MapQuest("ecfe7efc-9b38-459e-be4f-49053063aba8");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
